util.AddNetworkString("UpdateTurnOrderHUD")
util.AddNetworkString("UpdateRangeFinder")
util.AddNetworkString("PlayTurnSound")
util.AddNetworkString("UpdatePlayerMovement")
util.AddNetworkString("SetInitiativeVisible")