ITEM.name = "Carapace Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Standard carapace armor."
ITEM.longdesc = "A durable medium armor equipped with a respirator, providing protection against blasts and hazardous environments."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 16
ITEM.type = "Medium"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Blast-Resistant", "Respirator" }