ITEM.name = "Recon Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Stealth armor for reconnaissance."
ITEM.longdesc = "A lightweight armor equipped with stealth capabilities, photo-visor, and respirator for covert operations."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Tau"
ITEM.AP = 18
ITEM.type = "Light"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Stealth", "Photo-Visor", "Respirator"}
