ITEM.name = "Sniper-Guard Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Specialized for snipers."
ITEM.longdesc = "Designed for stealth and precision, this lightweight armor aids in covert operations while offering basic protection."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 10
ITEM.type = "Light"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Blast-Resistant", "Stealth"}
