ITEM.name = "Light-Flak Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl" -- On-ground model
ITEM.description = "A breastplate, shoulder pauldrons, knee plates, greaves and a helmet." -- Shows up when looked at on ground and in inventory
ITEM.longdesc = "Low-grade personal infantry armour. It consists of a breastplate, shoulder pauldrons, knee plates, greaves and a helmet - made from many layers of ablative and shock-absorbent materials. Solid hits from high impact weapons can generally negate it, and it is relatively lightweight, cheap to produce and dependable in most combat situations." -- Shows up when looked at in inventory
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true -- Include if armor is only usable by Humans, Abhumans, or Amphii 
ITEM.AP = 7 --Amount of armor, do not add extra points from Good or Best quality
ITEM.type = "Light" -- Light, Medium, Heavy, or Power
ITEM.quality = "Normal" -- Poor, Normal, Good, Best