ITEM.name = "Enforcer Light Carapace"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Stylish light carapace."
ITEM.longdesc = "Preferred by enforcers for its blend of protection and style, this armor is both fashionable and functional."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 10
ITEM.type = "Light"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Blast-Resistant", "Fashionable"}
