ITEM.name = "Wychsuit"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Flexible armor for Wych gladiators."
ITEM.longdesc = "A light and flexible armor providing stealth capabilities and an intimidating aura, tailored for Drukhari Wyches."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Eldar"
ITEM.AP = 20
ITEM.type = "Light"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Intimidating", "Stealth", "Wych" }