ITEM.name = "Holo-Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Advanced holographic armor."
ITEM.longdesc = "A light armor with stealth capabilities and a clone-field to confuse enemies."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 20
ITEM.type = "Light"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Stealth", "Clone-Field"}
