ITEM.name = "Guardian Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Advanced Guardian armor."
ITEM.longdesc = "Enhanced Wraithbone armor for Eldar Guardians, featuring minor runes, void-suit integration, and superior optics."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Eldar"
ITEM.AP = 22
ITEM.type = "Medium"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Wraithbone", "Minor-Runes", "Void-Suit", "Photo-Visor"}
