ITEM.name = "Ogryn's Plate"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Heavy armor for Ogryns."
ITEM.longdesc = "A heavy plate armor designed to withstand significant impacts and provide blast resistance."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 20
ITEM.type = "Heavy"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Blast-Resistant" }