ITEM.name = "Aspect Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Medium Eldar armor."
ITEM.longdesc = "Crafted from Wraithbone and inscribed with minor runes, this armor integrates void-suit capabilities and advanced optics."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Eldar"
ITEM.AP = 20
ITEM.type = "Medium"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Wraithbone", "Minor-Runes", "Void-Suit", "Photo-Visor"}
