ITEM.name = "Nob Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Thick Nob armour."
ITEM.longdesc = "Heavy-duty armour designed for Ork Nobz, offering excellent protection and durability."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Ork"
ITEM.AP = 20
ITEM.type = "Medium"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Skrapz", "Blast Resistant"}
