ITEM.name = "Water-Caste Dress"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Elegant attire for the Water-Caste."
ITEM.longdesc = "A fashionable dress with integrated medicae systems, reflecting the diplomatic and cultural role of the Water-Caste."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Tau"
ITEM.AP = 8
ITEM.type = "Light"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Fashionable", "Medicae"}
