ITEM.name = "Lucius-IX Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "A Lucius-IX power armor."
ITEM.longdesc = "Power armor that enhances psychic abilities, equipped with void-suit capabilities and advanced optics."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 25
ITEM.type = "Power"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Psi-Enhancing", "Void-Suit", "Photo-Visor"}
