ITEM.name = "Light Carapace Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Lightweight carapace armor."
ITEM.longdesc = "Designed for mobility, this armor provides reliable blast protection and respiratory support."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 12
ITEM.type = "Light"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Blast-Resistant", "Respirator" }