ITEM.name = "Xeno-Field"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Alien light force-field armor."
ITEM.longdesc = "This advanced light armor integrates alien technology to generate a force-field, offering excellent protection."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.AP = 25
ITEM.type = "Light"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Force-Field"}
