ITEM.name = "Galvanic Exo-Rainment MK-II"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Galvanic battle raiment."
ITEM.longdesc = "A reinforced heavy armor offering void protection and blast resistance, favored by advanced Mechanicus personnel."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 27
ITEM.type = "Heavy"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Void-Suit", "Photo-Visor", "Blast-Resistant" }