ITEM.name = "Auxiliary Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Standard issue for T'au auxiliaries."
ITEM.longdesc = "Medium armor designed for T'au auxiliaries, featuring integrated photo-visor and respirator for battlefield conditions."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Tau"
ITEM.AP = 15
ITEM.type = "Medium"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Photo-Visor", "Respirator" }