ITEM.name = "Guard Flak Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Standard Guard flak armor."
ITEM.longdesc = "Issued to the Imperial Guard, this flak armor provides reliable protection against shrapnel and light ballistic threats."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 14
ITEM.type = "Medium"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Blast-Resistant"}
