ITEM.name = "Heavy-Power Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "A heavily reinforced power armor."
ITEM.longdesc = "Heavy power armor offering exceptional blast resistance, void-suit capabilities, and advanced optics."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 30
ITEM.type = "Power"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Blast-Resistant", "Void-Suit", "Photo-Visor" }