ITEM.name = "PDF Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "A standard protective suit."
ITEM.longdesc = "Standard issue armor used by Planetary Defense Forces, offering moderate protection against explosive impacts."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 13
ITEM.type = "Heavy"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Blast-Resistant"}
