ITEM.name = "Civilian Attire"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Basic civilian clothing."
ITEM.longdesc = "Light and unassuming clothing for everyday wear, offering no protective features."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Tau"
ITEM.AP = 2
ITEM.type = "Light"
ITEM.quality = "Normal"
ITEM.specialQualities = {}
