ITEM.name = "Kabalite Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Armor worn by Kabalite warriors."
ITEM.longdesc = "A medium armor integrating void protection, blast resistance, and advanced optics, used by Drukhari Kabalites."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Eldar"
ITEM.AP = 22
ITEM.type = "Medium"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Void-Suit", "Blast-Resistant", "Photo-Visor", "Intimidating"}
