ITEM.name = "Scorpion Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Stealth-focused Eldar armor."
ITEM.longdesc = "This Wraithbone armor offers stealth, fashion, and superior void-suit capabilities, making it ideal for covert operations."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Eldar"
ITEM.AP = 20
ITEM.type = "Medium"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Wraithbone", "Minor-Runes", "Fashionable", "Void-Suit", "Stealth"}
