ITEM.name = "Ork-Iron Gob"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Iconic Ork gob armor."
ITEM.longdesc = "A large, intimidating gob-shaped plate that protects and terrifies enemies simultaneously."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Ork"
ITEM.AP = 22
ITEM.type = "Medium"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Skrapz", "Intimidating", "Blast Resistant"}
