ITEM.name = "Artificer-Class Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "A nullifying Artificer-Class power armor."
ITEM.longdesc = "Power armor designed to nullify psychic influences, with void-suit capabilities and advanced optics."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 27
ITEM.type = "Power"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Nullifying", "Void-Suit", "Photo-Visor" }