ITEM.name = "Aristocrat's Dress"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Elegant attire for the aristocracy."
ITEM.longdesc = "A lavish dress embedded with a force-field generator, providing protection and status for the elite."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 15
ITEM.type = "Light"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Force-Field"}
