ITEM.name = "Knightly Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "A suit of knightly armor."
ITEM.longdesc = "Heavy and imposing, this armor is both fashionable and intimidating, favored by noble warriors."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 15
ITEM.type = "Heavy"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Fashionable", "Intimidating" }