ITEM.name = "Mesh Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Light Eldar armor."
ITEM.longdesc = "A lightweight armor of Wraithbone reinforced with minor runes, equipped with a void-suit and enhanced optics."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Eldar"
ITEM.AP = 15
ITEM.type = "Light"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Wraithbone", "Minor-Runes", "Void-Suit", "Photo-Visor"}
