ITEM.name = "Light-Flak Cloak"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "A light-flak cloak."
ITEM.longdesc = "A relatively lightweight and fashionable cloak made from ablative and impact-absorbent materials, capable of deflecting and negating most small-arms, shrapnel and proximity blasts."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 5
ITEM.type = "Light"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Fashionable",}
