ITEM.name = "Bullgryn's Plate"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Imposing heavy plate armor."
ITEM.longdesc = "A massive heavy plate offering exceptional blast resistance and an intimidating presence."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 30
ITEM.type = "Heavy"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Blast-Resistant", "Intimidating" }