ITEM.name = "Gretchin Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Basic Gretchin protection."
ITEM.longdesc = "A crude and minimal armor piece used by Gretchins. Provides barely any protection but better than nothing."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Ork"
ITEM.AP = 2
ITEM.type = "Light"
ITEM.quality = "Normal"
ITEM.specialQualities = {  }
