ITEM.name = "Tech-Wright's Robes"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Robes worn by aspiring Tech-Wrights."
ITEM.longdesc = "Lightweight robes integrated with a respirator, commonly used by novice members of the Mechanicus."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 12
ITEM.type = "Light"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Respirator"}
