ITEM.name = "Ard Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Reinforced heavy armor."
ITEM.longdesc = "Built for toughness, this armor is a favorite among the most stubborn Orks."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Ork"
ITEM.AP = 23
ITEM.type = "Heavy"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Skrapz", "Blast Resistant" }
