ITEM.name = "Shadow Field"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "A unique field of shadows."
ITEM.longdesc = "A near-unique armor generating a shadow field for unparalleled defense and elusiveness."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Eldar"
ITEM.AP = 28
ITEM.type = "Unique"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Shadow-Field"}
