ITEM.name = "Ork Eavy Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Heavy Ork armor."
ITEM.longdesc = "Thick slabs of metal bolted together provide solid defense against most attacks."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Ork"
ITEM.AP = 20
ITEM.type = "Heavy"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Skrapz", "Blast Resistant" }
