ITEM.name = "Light-Flak Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "A breastplate, shoulder pauldrons, knee plates, greaves and a helmet."
ITEM.longdesc = "Low-grade personal infantry armour. It consists of a breastplate, shoulder pauldrons, knee plates, greaves and a helmet - made from many layers of ablative and shock-absorbent materials. Solid hits from high impact weapons can generally negate it, and it is relatively lightweight, cheap to produce and dependable in most combat situations."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true -- Poor, Normal, Good, Best
ITEM.AP = 7
ITEM.type = "Light"
ITEM.quality = "Normal"
