ITEM.name = "Mega Nob Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Massive Mega Nob armour."
ITEM.longdesc = "A mechanical suit of unparalleled strength and defense, used by the mightiest Ork Nobz."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Ork"
ITEM.AP = 30
ITEM.type = "Power"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Skrapz", "Intimidating", "Blast Resistant" }
