ITEM.name = "Ork Flak Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Crude Ork flak armor."
ITEM.longdesc = "This flak armor is built from scavenged materials, offering decent protection for Orks."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Ork"
ITEM.AP = 14
ITEM.type = "Medium"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Skrapz" }
