ITEM.name = "AB-Class Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Advanced medium armor for Abhumans."
ITEM.longdesc = "Medium armor with enhanced blast resistance and advanced optics."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 24
ITEM.type = "Medium"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Blast-Resistant", "Photo-Visor"}
