ITEM.name = "Flak Greatcoat"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "A large flak coat."
ITEM.longdesc = "Many Imperial Guard and PDF officers favour these heavy garments, as they offer protection against colder climates as well as enemy fire. Stylish as well as functional, they are also favourites among civilian fighters as well."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true -- Poor, Normal, Good, Best
ITEM.AP = 10
ITEM.type = "Heavy"
ITEM.quality = "Normal"
