ITEM.name = "Flak Jacket"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "A flak jacket."
ITEM.longdesc = "A flak jacket made from a combination of ablative and blast-absorbent materials, covering the body, arms, and legs - it is effective in protecting against small-arms and shrapnel, moreso against explosives as it is very blast-resistant."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 7
ITEM.type = "Medium"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Blast-Resistant",}
