ITEM.name = "Graia-Pattern Flak Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Advanced flak armor from Graia."
ITEM.longdesc = "Developed on Graia, this heavy flak armor incorporates advanced medicae systems and enhanced optics for battlefield superiority."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 15
ITEM.type = "Heavy"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Blast-Resistant", "Photo-Visor", "Medicae"}
