ITEM.name = "Flak Greatcoat"
ITEM.model = "models/props_c17/BriefCase001a.mdl" -- On-ground model
ITEM.description = "A large flak coat." -- Shows up when looked at on ground and in inventory
ITEM.longdesc = "Many Imperial Guard and PDF officers favour these heavy garments, as they offer protection against colder climates as well as enemy fire. Stylish as well as functional, they are also favourites among civilian fighters as well." -- Shows up when looked at in inventory
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true -- Include if armor is only usable by Humans, Abhumans, or Amphii 
ITEM.AP = 10 --Amount of armor, do not add extra points from Good or Best quality
ITEM.type = "Heavy" -- Light, Medium, Heavy, or Power
ITEM.quality = "Normal" -- Poor, Normal, Good, Best