ITEM.name = "Magos-Robes"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Ceremonial robes of a Magos."
ITEM.longdesc = "A unique and highly advanced armor with void protection, Mechanicus blessings, and a force-field generator."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 30
ITEM.type = "Light"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Void-Suit", "Photo-Visor", "Deus Mechanicus", "Force-Field"}
