ITEM.name = "Inquisitorial Power-Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "An Inquisitorial power armor."
ITEM.longdesc = "Unique power armor combining void-suit protection, an intimidating presence, and a fashionable design."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 32
ITEM.type = "Power"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Void-Suit", "Intimidating", "Fashionable" }