ITEM.name = "Heavy Carapace Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Heavy-duty carapace armor."
ITEM.longdesc = "This heavily reinforced armor offers exceptional blast protection and built-in respiratory systems."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 20
ITEM.type = "Heavy"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Blast-Resistant", "Respirator" }