ITEM.name = "Tuff-Boy Shaka Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Shaka armor for tough Orks."
ITEM.longdesc = "Heavily reinforced armor made for the toughest Orks, ready to face any threat."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Ork"
ITEM.AP = 25
ITEM.type = "Heavy"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Skrapz", "Blast Resistant"}
