ITEM.name = "Hospitalier Carapace"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Medicae-ready armor."
ITEM.longdesc = "Developed for the Adepta Sororitas Hospitalier, this armor integrates medicae systems with void-capable durability."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 23
ITEM.type = "Medium"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Medicae", "Void-Suit" }