ITEM.name = "Rune Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Unique Eldar armor."
ITEM.longdesc = "A unique armor made from Wraithbone, blending Asuryani runes, void protection, and an elegant design."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Eldar"
ITEM.AP = 22
ITEM.type = "Unique"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Wraithbone", "Fashionable", "Asuryani-Runes", "Void-Suit" }