ITEM.name = "Xenohide Tunic"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "A tunic made of durable xenohide."
ITEM.longdesc = "A light armor crafted from exotic xenohide, designed for stealth and creating an intimidating presence."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Various Xenos"
ITEM.AP = 18
ITEM.type = "Light"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Intimidating", "Stealth" }