ITEM.name = "Psychic-Bodyglove"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "A bodyglove that enhances psychic abilities."
ITEM.longdesc = "Light armor designed to augment the wearer's psychic abilities, enhancing their connection to the Warp."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 18
ITEM.type = "Light"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Psi-Enhancing" }