ITEM.name = "Gravis Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Gravis-class heavy power armor."
ITEM.longdesc = "The heaviest power armor available, featuring void-suit integration, Astartes enhancements, and unmatched blast resistance."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Astartes"
ITEM.AP = 36
ITEM.type = "Power"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Void-Suit", "Astartes", "Photo-Visor", "Blast-Resistant"}
