ITEM.name = "Volcanis Shroud"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "A shroud resistant to flames."
ITEM.longdesc = "Light armor that is both flame-resistant and fashionable, offering protection in high-temperature environments."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.AP = 14
ITEM.type = "Light"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Flame-Resistant", "Fashionable" }