ITEM.name = "Ghostplate Armour"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Ethereal armor with advanced protection."
ITEM.longdesc = "Heavy armor equipped with a void suit, forcefield generator, and advanced optics for superior defense."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = false
ITEM.race = "Eldar"
ITEM.AP = 25
ITEM.type = "Heavy"
ITEM.quality = "Normal"
ITEM.specialQualities = { "Void-Suit", "Addendum-Forcefield", "Photo-Visor", "Intimidating" }