ITEM.name = "Armor Name"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "Description"
ITEM.longdesc = "Long Description."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.humanOnly = true
ITEM.race = "Gland Warrior"
ITEM.AP = 5
ITEM.type = "Power"
ITEM.quality = "Normal"
ITEM.specialQualities = {"Fashionable", "Void Suit", "Photo-Visor", "Blast-Resistant", "Respirator", "Medicae", "Wraithbone", "Asuryani-Runes", "Teleportarium", "Minor-Runes", "Stealth", "Skrapz", "Intimidating", "Shadow-Field", "Clone-Field", "Wych", "Force-field", "Disgusting", "Deus Mechanicus", "Psi-Enhancing", "Nullifying", "Flame Absorbing", "Weather-Resistant", "Navis-Nobilite", "Aquatic", "Astartes",}
