ITEM.name = "Light Armorjack"
ITEM.model = "models/props_c17/BriefCase001a.mdl"
ITEM.description = "A set of lightweight armor weave."
ITEM.longdesc = "A combination of Kevlar and plastic meshes inserted into the weave of the fabric. It tends to stick out somewhat as being lined with something."
ITEM.height = 2
ITEM.width = 2
ITEM.isArmor = true
ITEM.isBodyArmor = true
ITEM.AP = 5
ITEM.type = "Power"
ITEM.quality = "Normal"
ITEM.newSkin = 0
ITEM.bodygroupsub = {0}
ITEM.specialQualities = {"Spooky", "Fashionable", "Medicae"}
