ITEM.name = "Archeotech Laspistol"
ITEM.description = "Class: Pistol | Range: 90m | Rate of Fire: S/3/- | Damage: 1d10+3 E | Penetration: 2 | Capacity: 70 | Reload: Full | Special: Accurate, Reliable | Availability: Near Unique"
ITEM.longdesc = "The Archeotech Laspistol is an ancient and powerful weapon of mysterious origin, imbued with unmatched craftsmanship."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_tfa_vosslaspistol"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 3
