ITEM.name = "sh_ardboy_choppa"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10+7 R | Penetration: 4 | Capacity: - | Reload: - | Special: Orkish, Unbalanced | Availability: Scarce"
ITEM.longdesc = "Ardboy Choppa is an Orkish weapon with crude but effective capabilities."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "arc9_wk_ork_choppanob"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
