ITEM.name = "Archeotech Power Sword"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 2d10+6 E | Penetration: 5 | Capacity: - | Reload: - | Special: Powerfield/Balanced/Defensive | Availability: Unique"
ITEM.longdesc = "A power sword that was almost forgotten to time in how to replicate, but once it was discovered, manufacturing began again. Though with how detailed and taxing it is to make, only a few have been created. This makes all other power swords grimace with it's destructive potential."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_power-sword_veteran"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1