ITEM.name = "Assault Flamer"
ITEM.description = "Class: Basic | Range: 10m | Rate of Fire: S/-/- | Damage: 1d10+4 E | Penetration: 1 | Capacity: 12 | Reload: 3 Full | Special: Flame | Availability: Scarce"
ITEM.longdesc = "A weapon designed for specific usage in combat scenarios."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_adp-ss_hand-flamethrower"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
