ITEM.name = "Archeotech Chainsword"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 2d10+5 R | Penetration: 6 | Capacity: - | Reload: - | Special: Tearing/Balanced | Availability: Unique"
ITEM.longdesc = "A chainsword that was almost forgotten to time in how to replicate, but once it was discovered, manufacturing began again. Though with how detailed and taxing it is to make, only a few have been created. This makes all other Chainswords grimace with it's destructive potential."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "chainsword"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
