ITEM.name = "Boltgun Locke"
ITEM.description = "Class: Basic | Range: 90m | Rate of Fire: S/2/4 | Damage: 1d10+5 X | Penetration: 4 | Capacity: 24 | Reload: Full | Special: Tearing | Availability: Very Rare"
ITEM.longdesc = "A reliable bolter variant known for its accuracy and stopping power."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_inq-st_bolter"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 2
ITEM.auto = 4
