ITEM.name = "Boltgun Footfall"
ITEM.description = "Class: Basic | Range: 80m | Rate of Fire: S/3/- | Damage: 1d10+4 X | Penetration: 2 | Capacity: 18 | Reload: Full | Special: Tearing / Unreliable | Availability: Rare"
ITEM.longdesc = "A standard issue firearm for Space Marines, delivering explosive bolt rounds."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_zad_stormbolter"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 3
