ITEM.name = "Boarding Gun"
ITEM.description = "Class: Basic | Range: 30m | Rate of Fire: S/3/- | Damage: 1d10+5 I | Penetration: 1 | Capacity: 3 | Reload: 2 Full | Special: Inaccurate/Tearing/Scatter | Availability: Scarce"
ITEM.longdesc = "The cramped hallways of the ship might be a problem... but people won't be with this."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "arccw_apex_mastiff"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 3
