ITEM.name = "Bola Launcher"
ITEM.description = "Class: Basic | Range: 20m | Rate of Fire: S/-/- | Damage: 1d10 I | Penetration: 0 | Capacity: 6 | Reload: Full | Special: Primitive / Snare | Availability: Scarce"
ITEM.longdesc = "A weapon designed for specific usage in combat scenarios."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "sfw_thunderbolt"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
