ITEM.name = "Bolt Carbine Ceres"
ITEM.description = "Class: Basic | Range: 90m | Rate of Fire: S/2/- | Damage: 1d10+5 X | Penetration: 4 | Capacity: 12 | Reload: 2 Full | Special: Reliable / Tearing | Availability: Very Rare"
ITEM.longdesc = "A lighter, more compact version of the standard bolter for quick skirmishes."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_primaris_bolter-carabine"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 2
