ITEM.name = "Burst Cannon"
ITEM.description = "Class: Basic | Range: 60m | Rate of Fire: -/3/6 | Damage: 2d10+3 E | Penetration: 4 | Capacity: 40 | Reload: 2 Full | Special: - | Availability: Very Rare"
ITEM.longdesc = "A large plasma weapon, sending a burst of energy to rip someone apart. Or turn them to blue ash, whichever comes first."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "arccw_apex_tripletake"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 3
ITEM.auto = 6
