ITEM.name = "Chainfist (Unpowered)"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 2d10+5 I | Penetration: 5 | Capacity: - | Reload: - | Special: Balanced/Defensive/Crippling | Availability: Extremely Rare"
ITEM.longdesc = "A fist with a chainsaw, pretty straight forward. At the moment it's unpowered, but it will still hit quite hard and function as a blocking gauntlet."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_bo3_chainsaw"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1