ITEM.name = "Chainfist (Powered)"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 2d10+10 R | Penetration: 8 | Capacity: - | Reload: - | Special: Balanced/Tearing/Crippling | Availability: -"
ITEM.longdesc = "A fist with a chainsaw, pretty straight forward. It's been revved up with power, and this compact chain can rip through plenty of targets without even pausing."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_bo3_chainsaw"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
