ITEM.name = "Chainsword Hydrapur"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10+3 R | Penetration: 2 | Capacity: - | Reload: - | Special: Tearing | Availability: Scarce"
ITEM.longdesc = "Another pattern of chainsword with a bit more style. Still cuts the same."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "chainsword"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
