ITEM.name = "Cyclic Ion Gun"
ITEM.description = "Class: Heavy | Range: 50m | Rate of Fire: S/3/6 | Damage: 2d10+5 E | Penetration: 6 | Capacity: 100 | Reload: 2 Full | Special: Overcharge (4) | Availability: Near Unique"
ITEM.longdesc = "The culmination of the Syrr'Tok and the Water Caste. Rends through multiple targets of lightly armored targets."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "arc9_wk_pers_henai_lasminigun"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 3
ITEM.auto = 6
