ITEM.name = "Compound Bow"
ITEM.description = "Class: Basic | Range: 40m | Rate of Fire: S/-/- | Damage: 2d10 R| Penetration: 2 | Capacity: 1 | Reload: Half | Special: Primitive | Availability: Very Rare"
ITEM.longdesc = "The true hunter's choice."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "arccw_apex_bocek"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
