ITEM.name = "Demiklaive"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10+5 E | Penetration: 8 | Capacity: - | Reload: - | Special: Powerfield, Balanced | Availability: Unique"
ITEM.longdesc = "The Demiklaive is a balanced melee weapon infused with a power field, making it a deadly tool in close combat."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "melee_eldars_incub_long-power-sword"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
