ITEM.name = "Dvorgite Skinner"
ITEM.description = "Class: Heavy | Range: 15m | Rate of Fire: S/-/- | Damage: 3d10 E | Penetration: 5 | Capacity: 5 | Reload: 2 Full | Special: Flame | Availability: Extremely Rare"
ITEM.longdesc = "A weapon named after the xenos race that created it, this odd weapon utilizes biological material to create a white hot stream of energy. Surprisingly, it does in fact skin."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "sfw_umbra"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
