ITEM.name = "Disposable Handgun"
ITEM.description = "Class: Pistol | Range: 30m | Rate of Fire: S/2/- | Damage: 1d10+2 I | Penetration: 0 | Capacity: 8 | Reload: 2 Full | Special: Inaccurate/Unreliable | Availability: Ubiquitous"
ITEM.longdesc = "A dinky, pipe pistol. Perfect to murder someone for their thrones and ditch it."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_rustalpha_revolver"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 2
