ITEM.name = "Disposable Launcher"
ITEM.description = "Class: Heavy | Range: 200m | Rate of Fire: S/-/- | Damage: 1d10+3 X | Penetration: 1 | Capacity: N/A | Reload: - | Special: Useless after one use. | Availability: Rare"
ITEM.longdesc = "A weapon designed for specific usage in combat scenarios."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "arc9_wk_ork_rocketlauncher"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
