ITEM.name = "Drusian Chainsword"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10+3 R | Penetration: 1 | Capacity: - | Reload: - | Special: Tearing/Balanced | Availability: Average"
ITEM.longdesc = "An even more elegent and dualist built weapon with a steady weight. Somehow in this day and age, this is classified as elegent."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "zad_eldar_chainsword"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
