ITEM.name = "Eldar Biting Blade"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10+6 R | Penetration: 2 | Capacity: - | Reload: - | Special: Tearing, Unbalanced | Availability: Unique"
ITEM.longdesc = "The Eldar Biting Blade is a two-handed melee weapon designed to rip through enemy armor and flesh with its brutal attacks."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "zad_eldar_biting_blade"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
