ITEM.name = "Fusion Cascade"
ITEM.description = "Class: Heavy | Range: 16m | Rate of Fire: -/3/6 | Damage: 1d10+12 E | Penetration: 12 | Capacity: 16 | Reload: 2 Full | Special: Melta | Availability: Near Unique"
ITEM.longdesc = "A close range remover, of energy cycling around before crashing into the poor victim. Or justified victim. Who am I to judge."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "sfw_saphyre"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 3
ITEM.auto = 6