ITEM.name = "Flameburst"
ITEM.description = "Class: Basic | Range: 40m | Rate of Fire: S/-/- | Damage: 1d10+4 E | Penetration: 2 | Capacity: 6 | Reload: 2 Full | Special: Flame / Recharge | Availability: Rare"
ITEM.longdesc = "An advanced version of a flamethrower with a powerful burst of fire."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_astra_flamethrower"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
