ITEM.name = "Flamer Mezoa"
ITEM.description = "Class: Basic | Range: 20m | Rate of Fire: S/-/- | Damage: 1d10+4 E | Penetration: 2 | Capacity: 6 | Reload: 2 Full | Special: Flame | Availability: Scarce"
ITEM.longdesc = "A weapon designed for specific usage in combat scenarios."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "zad_eldar_flamer"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
