ITEM.name = "Ghost Sword"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 2d10+3 E | Penetration: 6 | Capacity: - | Reload: - | Special: Powerfield/Balanced | Availability: Extremely Rare"
ITEM.longdesc = "An Asuryani with a Spirit Stone in the weapon itself. This one in particular is a sword version, and generates a power field. If you're not an Asuryani yourself, best not show this to another."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "melee_eldars_power-sword_banshee"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1