ITEM.name = "Galthite Lacerator"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10+6 R | Penetration: 6 | Capacity: - | Reload: - | Special: Tearing | Availability: Near Unique"
ITEM.longdesc = "A fist like weapon created by a xenos race that it's named after. These blades slice through flesh with such ease, it's rumored that heretics copy the same..."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_bo3_boneglass"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
