ITEM.name = "Hexrifle"
ITEM.description = "Class: Basic | Range: 180m | Rate of Fire: S/-/- | Damage: 1d10+1 I | Penetration: 2 | Capacity: 1 | Reload: 3 Full | Special: Accurate, Hexing, Felling 2 | Availability: Very Rare"
ITEM.longdesc = "The Hexrifle is an accurate long-range weapon that can pierce through enemy armor and weaken their resolve."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "sfw_rattatat"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
