ITEM.name = "Heavy Shredder"
ITEM.description = "Class: Heavy | Range: 80m | Rate of Fire: S/-/- | Damage: 3d10+5 R | Penetration: 2 | Capacity: 12 | Reload: 2 Full | Special: Reliable, Blast 4, Tearing | Availability: Near Unique"
ITEM.longdesc = "The Heavy Shredder is a devastating heavy weapon capable of tearing through enemies with its high rate of fire and large area of effect."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_zad_heavybolter"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
