ITEM.name = "Heavy Fusion Gun"
ITEM.description = "Class: Heavy | Range: 30m | Rate of Fire: S/-/- | Damage: 2d10+9 E | Penetration: 13 | Capacity: 10 | Reload: 3 Full | Special: Reliable, Melta | Availability: Near Unique"
ITEM.longdesc = "The Heavy Fusion Gun is a powerful anti-armor weapon that excels in close-range destruction, capable of melting through even the toughest targets."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_vj_lub_megadeffgun"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
