ITEM.name = "Heavy Webber"
ITEM.description = "Class: Heavy | Range: 70m | Rate of Fire: S/-/- | Damage: 1d5+4 R | Penetration: 1 | Capacity: 5 | Reload: 4 Full | Special: Snare/Unwieldy/Blast 5 | Availability: Rare"
ITEM.longdesc = "An even larger piece of Webber equipment. Unlike all the rest before it, this was meant to be mounted on pieces of armor and send out even more thicker pieces of restraining webbing. It's not surprising this causes accidental deaths to the targets. At least, that's what the police say."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "sfw_stinger"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1