ITEM.name = "Howler"
ITEM.description = "Class: Thrown | Range: SBx3 | Rate of Fire: S/-/- | Damage: 3d10 X | Penetration: 1 | Capacity: - | Reload: - | Special: Blast 3/Shocking | Availability: Scarce"
ITEM.longdesc = "A grenade named for the fact that whoever ends up getting a fragment of it buried in, is rendered into a painful stun."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "wk_grenade_emp"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
