ITEM.name = "Heavy Boltpistol"
ITEM.description = "Class: Pistol | Range: 50m | Rate of Fire: S/2/- | Damage: 2d10+5 X | Penetration: 5 | Capacity: 14 | Reload: Full | Special: Accurate/Tearing/Reliable | Availability: Extremely Rare"
ITEM.longdesc = "A boltpistol made of even more robust material, with a bigger magazine and a larger caliber."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_zad_primaris_boltheavypistol"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 2
