ITEM.name = "Heavy Bolter"
ITEM.description = "Class: Heavy | Range: 100m | Rate of Fire: -/4/8 | Damage: 2d10+6 X | Penetration: 6 | Capacity: 80 | Reload: 3 Full | Special: Twin-Linked/Accurate/Reliable | Availability: Unique"
ITEM.longdesc = "A massive bolter, with a massive magazine and two barrels to double up the rate of fire. None shall stand."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_hwh40k_heavybolter"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 4
ITEM.auto = 8
