ITEM.name = "Hellpistol Lucius"
ITEM.description = "Class:Pistol | Range: 35m | Rate of Fire: S/2/- | Damage: 1d10+4 E | Penetration: 7 | Capacity: 40 | Reload: 2 Full | Special: - | Availability: Rare"
ITEM.longdesc = "The Lucius-pattern Hellpistol delivers high energy shots capable of penetrating even power armor."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_tfa_vosslaspistol"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 2
