ITEM.name = "Inertial Hammer"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10+7 I | Penetration: 3 | Capacity: - | Reload: - | Special: Unwieldy | Availability: Near Unique"
ITEM.longdesc = "One of the many artifacts of Dead Worlds. This hammer slams with somehow exponentially more energy than it began with, and can burst tank armor."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_swen_hammer"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1