ITEM.name = "Ikanos Boltpistol"
ITEM.description = "Class: Pistol | Range: 40m | Rate of Fire: S/-/- | Damage: 1d10+6 X | Penetration: 3 | Capacity: 15 | Reload: Full | Special: Accurate/Tearing | Availability: Very Rare"
ITEM.longdesc = "A compact boltpistol that is aged back towards the Great Crusade. The caliber is the same as a .50 cal."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_primaris_boltpistol"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
