ITEM.name = "Kroot Hunting Rifle"
ITEM.description = "Class: Basic | Range: 150m | Rate of Fire: S/-/- | Damage: 1d10+5 E | Penetration: 3 | Capacity: 8 | Reload: Full | Special: Accurate | Availability: Extremely Rare"
ITEM.longdesc = "The energy rifle with wooden furniture. Despite looking crude, it's still quite accurate. Perfect for hunting."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_taupulserifle"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
