ITEM.name = "Knife"
ITEM.description = "Class: Melee/Thrown | Range: 5m | Rate of Fire: - | Damage: 1d5 R | Penetration: 0 | Capacity: - | Reload: - | Special: Primitive | Availability: Plentiful"
ITEM.longdesc = "A metal blade, for utility and harm. The reliable backup. Or your first choice, if you're that insane."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_zad_combatknife"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
