ITEM.name = "Krak"
ITEM.description = "Class: Thrown | Range: SBx3 | Rate of Fire: S/-/- | Damage: 2d10+4 X | Penetration: 6 | Capacity: - | Reload: - | Special: Blast 1 | Availability: Rare"
ITEM.longdesc = "The infamous Krak Grenade. Armor is nothing."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "wk_grenade_krak"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
