ITEM.name = "sh_killsaw"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10+1 R | Penetration: 5 | Capacity: - | Reload: - | Special: Orkish, Razorsharp, Bleeding | Availability: Scarce"
ITEM.longdesc = "Killsaw is an Orkish weapon with crude but effective capabilities."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_nmrih_chainsaw"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
