ITEM.name = "Kroot Rifle"
ITEM.description = "Class: Basic | Range: 110m | Rate of Fire: S/2/- | Damage: 1d10+5 E | Penetration: 1 | Capacity: 6 | Reload: 2 Full | Special: Accurate | Availability: Very Rare"
ITEM.longdesc = "The rough looking but still quite capable kroot rifle. Perfect for hunting game of all sizes. Four legs, six, two."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "arccw_apex_3030"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 2