ITEM.name = "Lasgun"
ITEM.description = "Class: Basic | Range: 100m | Rate of Fire: S/3/- | Damage: 1d10+3 E | Penetration: 0 | Capacity: 60 | Reload: Full | Special: Reliable | Availability: Common"
ITEM.longdesc = "The Lasgun is the standard-issue infantry weapon of the Astra Militarum, known for its reliability and ease of use."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_tfa_vosslasgun"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 3
