ITEM.name = "Longlas"
ITEM.description = "Class: Basic | Range: 150m | Rate of Fire: S/-/- | Damage: 1d10+5 E | Penetration: 5 | Capacity: 40 | Reload: 2 Full | Special: Reliable, Accurate | Availability: Scarce"
ITEM.longdesc = "The Longlas is a sniper variant of the Lasgun, prized for its precision and increased power."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_tfa_vosslonglas"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
