ITEM.name = "Lucian Chain Axe"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10+5 R | Penetration: 0 | Capacity: - | Reload: - | Special: Tearing/Balanced | Availability: Average"
ITEM.longdesc = "A chain axe dedicated entirely on making the chainblade ripping through even faster than other generic models, at the cost of being less sturdier material."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_zad_chainaxe"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1