ITEM.name = "Lascarbine Locke"
ITEM.description = "Class: Basic | Range: 60m | Rate of Fire: S/2/- | Damage: 1d10+3 E | Penetration: 0 | Capacity: 40 | Reload: 2 Full | Special: Reliable, Accurate | Availability: Scarce"
ITEM.longdesc = "The Lascarbine Locke is a lightweight las weapon designed for greater mobility without sacrificing accuracy."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_tfa_vosslascarbine"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 2
