ITEM.name = "Lightning Claws"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 4d10+2 E | Penetration: 10 | Capacity: - | Reload: - | Special: Powerfield | Availability: Unique"
ITEM.longdesc = "The infamous Lightning Claws, large talons with a powerfield rippling through each of them. They will cut clean through whatever's in the way. Metal, fabric, or flesh."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "keller_claws"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
