ITEM.name = "Laspistol"
ITEM.description = "Class: Pistol | Range: 40m | Rate of Fire: S/-/- | Damage: 1d10+2 E | Penetration: 0 | Capacity: 30 | Reload: Full | Special: Reliable | Availability: Common"
ITEM.longdesc = "The Laspistol is a compact and reliable sidearm used across the Imperium, ideal for self-defense and close-quarters combat."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_tfa_vosslaspistol"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
