ITEM.name = "Longshot Pulse Rifle"
ITEM.description = "Class: Basic | Range: 200m | Rate of Fire: S/2/- | Damage: 2d10+3 E | Penetration: 4 | Capacity: 12 | Reload: 2 Full | Special: Accurate/Tearing | Availability: Near Unique"
ITEM.longdesc = "An even more finely tuned pulse rifle. Because clearly, they need to hit even more accurately."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_impulse_rifle"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 2