ITEM.name = "Mortar Locke"
ITEM.description = "Class: Heavy | Range: 50-300m | Rate of Fire: S/-/- | Damage: 2d10 X | Penetration: 2 | Capacity: 1 | Reload: Full | Special: Inaccurate / Shocking / Blast 4 | Availability: Rare"
ITEM.longdesc = "A weapon designed for specific usage in combat scenarios."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "wk_mortar_constructor"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
