ITEM.name = "Mezoa Lascutter"
ITEM.description = "Class: Heavy | Range: 5m | Rate of Fire: S/-/- | Damage: 2d10+3 E | Penetration: 6 | Capacity: 10 | Reload: 2 Full | Special: - | Availability: Rare"
ITEM.longdesc = "The Mezoa Lascutter is a heavy industrial tool adapted for combat, capable of cutting through thick armor."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_tfa_vosslascutter"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
