ITEM.name = "Mole Mortar"
ITEM.description = "Class: Heavy | Range: 50-200m | Rate of Fire: S/-/- | Damage: 2d10+2 X | Penetration: 2 | Capacity: 1 | Reload: Full | Special: Inaccurate / Shocking / Blast 4 | Availability: Extremely Rare"
ITEM.longdesc = "A siege weapon designed to burrow and explode under enemy positions."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "wk_mortar_constructor"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
