ITEM.name = "Musket"
ITEM.description = "Class: Pistol | Range: 30m | Rate of Fire: S/-/- | Damage: 1d10+2 I| Penetration: 0 | Capacity: 1 | Reload: 3 Full | Special: Primitive/Unreliable/Inaccurate | Availability: Common"
ITEM.longdesc = "A blackpowder rifle. Don't miss. And if you do, you'll have plenty of time to think about it."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_rustalpha_bolt_action_rifle"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
