ITEM.name = "Meltagun Mars"
ITEM.description = "Class: Basic | Range: 20m | Rate of Fire: S/-/- | Damage: 2d10+8 E | Penetration: 13 | Capacity: 5 | Reload: 2 Full | Special: Melta | Availability: Rare"
ITEM.longdesc = "A deadly weapon capable of melting through armor with superheated energy."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_zad_meltacadia"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
