ITEM.name = "Missile Launcher Retobi"
ITEM.description = "Class: Heavy | Range: 200m | Rate of Fire: S/-/- | Damage: See the missile table. | Penetration: See the missile table. | Capacity: 5 | Reload: 2 Full | Special: See the missile table. | Availability: Rare"
ITEM.longdesc = "A weapon designed for specific usage in combat scenarios."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_vj_lub_gangautogun"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
