ITEM.name = "Nandueshi Twinblade"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10+8 R | Penetration: 0 | Capacity: - | Reload: - | Special: Balanced/Tearing | Availability: Rare"
ITEM.longdesc = "A hilt with two blades on either end. Stylized similar to Asuryani weapons, but whoever makes them clearly didn't know how properly they're made. Still hits heavy, however."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "melee_eldars_incub_long-power-sword"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1