ITEM.name = "Nadueshi Twinblade"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10+6 R | Penetration: 0 | Capacity: - | Reload: - | Special: Balanced/Tearing | Availability: Rare"
ITEM.longdesc = "An intimidating pair of blades on both ends of shaft. Large sweeping hits."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "melee_eldars_incub_long-power-sword"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1