ITEM.name = "Needle Rifle"
ITEM.description = "Class: Basic | Range: 180m | Rate of Fire: S/-/- | Damage: 1d10+2 R | Penetration: 1 | Capacity: 6 | Reload: 2 Full | Special: Accurate/Toxic | Availability: Very Rare"
ITEM.longdesc = "An assassin's favorite delivery device. Delivers toxic agents to the target in a crystallized form, but with much more velocity to do it from range."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "sfw_hornet"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1