ITEM.name = "Naval Pistol Mars"
ITEM.description = "Class: Pistol | Range: 20m | Rate of Fire: S/3/- | Damage: 1d10+4 I | Penetration: 0 | Capacity: 6 | Reload: Full | Special: Tearing | Availability: Scarce"
ITEM.longdesc = "A naval officer's personal friend. For when they're boarded, or when a crewmember thinks they can perform a mutiny."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "arccw_apex_wingman"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 3
