ITEM.name = "sh_ork_shoota"
ITEM.description = "Class: Basic | Range: 60m | Rate of Fire: S/3/10 | Damage: 1d10+4 I | Penetration: 0 | Capacity: 30 | Reload: Full | Special: Inaccurate, Orkish | Availability: Scarce"
ITEM.longdesc = "Ork Shoota is an Orkish weapon with crude but effective capabilities."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "sfw_rattatat"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 3
ITEM.auto = 10
