ITEM.name = "Onager Gauntlet"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 3d10+10 E | Penetration: 10 | Capacity: - | Reload: - | Special: Power Field/Unwieldy/Shocking | Availability: Unique"
ITEM.longdesc = "A giant gauntlet, audibly sizziling with potential energy stored and ready to explode against a target. The T'au are weaker at close range, not weak."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "arc9_wk_ork_kibork_fists"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
