ITEM.name = "Omnissian Maul"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 2d10+5 I | Penetration: 8 | Capacity: - | Reload: - | Special: Powerfield/Unbalanced/Mechanicus | Availability: Extremely Rare"
ITEM.longdesc = "The hefty weight of the Omnissia is behind your strike. "
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "arc9_wk_eccl_maul"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
