ITEM.name = "sh_ork_choppa"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10+1 R | Penetration: 2 | Capacity: - | Reload: - | Special: Unbalanced, Orkish | Availability: Scarce"
ITEM.longdesc = "Ork Choppa is an Orkish weapon with crude but effective capabilities."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "arc9_wk_ork_choppa"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
