ITEM.name = "Officer's Cutlass"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10 R | Penetration: 0 | Capacity: - | Reload: - | Special: Shocking | Availability: Scarce"
ITEM.longdesc = "A not so impressive blade in combat, but a very threatening weapon to insubordinate soliders."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "lanius_swd"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1