ITEM.name = "Pulse Carbine"
ITEM.description = "Class: Basic | Range: 60m | Rate of Fire: S/-/3 | Damage: 2d10+2 E | Penetration: 4 | Capacity: 24 | Reload: Half | Special: Gyro-Stabilized | Availability: Very Rare"
ITEM.longdesc = "The automatic option for the fire caste. Surprisingly stable even when magdumping."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_impulse_carabine"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
ITEM.auto = 3
