ITEM.name = "Plasma Pistol Ryza"
ITEM.description = "Class: Pistol | Range: 30m | Rate of Fire: S/2/- | Damage: 1d10+6 E | Penetration: 6 | Capacity: 10 | Reload: 3 Full | Special: Overheat | Availability: Very Rare"
ITEM.longdesc = "A plasma weapon used by officers and elite troops, prone to overheating."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_zad_plasmapistol"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 2
