ITEM.name = "Pulse Pistol"
ITEM.description = "Class: Pistol | Range: 40m | Rate of Fire: S/2/- | Damage: 2d10+2 E | Penetration: 4 | Capacity: 16 | Reload: Half | Special: Gyro-Stabilized | Availability: Very Rare"
ITEM.longdesc = "For being a pistol, the pulse pistol still sends plasma over a shockingly far range."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_impulse_pistol"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 2