ITEM.name = "Power Sword Mordian"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10+5 E | Penetration: 5 | Capacity: - | Reload: - | Special: Powerfield/Balanced | Availability: Very Rare"
ITEM.longdesc = "A very balanced blade that is dedicated to dueling a foe with the added benefit of utterly cutting through them on the simpliest strike."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_zad_powersword"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
