ITEM.name = "sh_pistolz_zzap_gun"
ITEM.description = "Class: Pistol | Range: 35m | Rate of Fire: S/-/- | Damage: 2d10+2 E | Penetration: 1 | Capacity: 5 | Reload: 3 Full | Special: Overheat, Orkish, Shock | Availability: Scarce"
ITEM.longdesc = "Pistolz Zzap Gun is an Orkish weapon with crude but effective capabilities."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "arc9_wk_ork_bigmek_zzapgun"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
