ITEM.name = "Retribution"
ITEM.description = "Class: Basic | Range: 90m | Rate of Fire: S/-/- | Damage: 1d10+3 E | Penetration: 0 | Capacity: 10 | Reload: Full | Special: Accurate | Availability: Very Rare"
ITEM.longdesc = "The Retribution is a rare and finely crafted long-range las weapon designed for precision."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_tfa_vosslonglas"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
