ITEM.name = "Ripper Pistol"
ITEM.description = "Class: Pistol | Range: 30m | Rate of Fire: S/2/- | Damage: 1d10+3 I | Penetration: 7 | Capacity: 8 | Reload: Full | Special: Tearing/Toxic | Availability: Extremely Rare"
ITEM.longdesc = "A heavy pistol, that literally rips through armor and sinks in deep. The person underneath, will not last against the venomous payload."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_bolt_pistol"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 2
