ITEM.name = "Sword"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10 R | Penetration: 0 | Capacity: - | Reload: - | Special: Primitive/Balanced | Availability: Common"
ITEM.longdesc = "A true vanguard weapon. Or the fool's, who thinks he's the hero."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_inquisition_sword"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
