ITEM.name = "Shotlas"
ITEM.description = "Class: Basic | Range: 20m | Rate of Fire: S/3/- | Damage: 1d10+4 E | Penetration: 1 | Capacity: 40 | Reload: 2 Full | Special: - | Availability: Scarce"
ITEM.longdesc = "The Shotlas is a short-range variant of the Lasgun optimized for burst damage in tight spaces."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_tfa_vosslasgun"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 3
