ITEM.name = "Shuriken Pistol"
ITEM.description = "Class: Pistol | Range: 30m | Rate of Fire: S/3/5 | Damage: 1d10+2 R | Penetration: 4 | Capacity: 40 | Reload: 2 Full | Special: Reliable | Availability: Very Rare"
ITEM.longdesc = "The Shuriken Pistol is a finely crafted weapon known for its precision and reliability in combat."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "zad_eldar_shuriken_pistol"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 3
ITEM.auto = 5
