ITEM.name = "Storm Bolter Mars"
ITEM.description = "Class: Basic | Range: 90m | Rate of Fire: S/2/4 | Damage: 1d10+5 X | Penetration: 4 | Capacity: 60 | Reload: Full | Special: Storm / Tearing | Availability: Extremely Rare"
ITEM.longdesc = "A rapid-fire bolter variant, capable of unleashing a storm of bolts."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_adp-ss_stormbolter"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 2
ITEM.auto = 4
