ITEM.name = "Splinter Cannon"
ITEM.description = "Class: Heavy | Range: 110m | Rate of Fire: -/-/10 | Damage: 1d10+5 R | Penetration: 4 | Capacity: 300 | Reload: 3 Full | Special: Toxic | Availability: Near Unique"
ITEM.longdesc = "The Splinter Cannon is a rapid-fire heavy weapon that delivers toxic projectiles over long distances, designed for crowd control."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_vj_lub_eldarshurcannon"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
ITEM.auto = 10
