ITEM.name = "Shuriken Catapult"
ITEM.description = "Class: Basic | Range: 60m | Rate of Fire: S/3/10 | Damage: 1d10+4 R | Penetration: 6 | Capacity: 100 | Reload: 2 Full | Special: Reliable | Availability: Very Rare"
ITEM.longdesc = "The Shuriken Catapult is a rapid-firing weapon that excels in medium-range combat with high precision and reliability."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "zad_eldar_shuriken_catapult"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 3
ITEM.auto = 10
