ITEM.name = "Stutter-Las"
ITEM.description = "Class: Pistol | Range: 35m | Rate of Fire: S/-/5 | Damage: 1d10+2 E | Penetration: 0 | Capacity: 25 | Reload: Full | Special: Inaccurate | Availability: Average"
ITEM.longdesc = "A rapid-fire las weapon prone to overheating but capable of high sustained firepower in short bursts."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_tfa_vosslaspistol"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
ITEM.auto = 5
