ITEM.name = "sh_skorcha"
ITEM.description = "Class: Heavy | Range: 10m | Rate of Fire: S/-/- | Damage: 2d10+8 E | Penetration: - | Capacity: 2 | Reload: Full | Special: Orkish, Flame, Unwieldy, Customised | Availability: Rare"
ITEM.longdesc = "Skorcha is an Orkish weapon with crude but effective capabilities."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_inq-st_heavy-flamethrower"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
