ITEM.name = "Shock-Staff"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d5+3 I | Penetration: 0 | Capacity: - | Reload: - | Special: Shocking | Availability: Rare"
ITEM.longdesc = "A metal shaft that is entirely meant to pacify and put down rioters. Not meant to kill but, if you hit hard enough..."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_bo3_shockbaton"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1