ITEM.name = "Shotgun Persecutor"
ITEM.description = "Class: Basic | Range: 35m | Rate of Fire: S/3/- | Damage: 1d10+4 I | Penetration: 0 | Capacity: 20 | Reload: Full | Special: Reliable/Scatter | Availability: Rare"
ITEM.longdesc = "A bigger shotgun, meant to put down plenty of people down. Probably nonviolent protestors."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "weapon_inq-st_shotgun"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 3
