ITEM.name = "Sniper Rifle"
ITEM.description = "Class: Basic | Range: 220m | Rate of Fire: S/-/- | Damage: 1d10+5 I | Penetration: 2 | Capacity: 6 | Reload: Full | Special: Accurate | Availability: Rare"
ITEM.longdesc = "A heavy action sniper. It's almost comedic how big this is... but with the targets you're dealing with..."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "arccw_apex_kraber"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
