ITEM.name = "Truncheon"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10 I | Penetration: 0 | Capacity: - | Reload: - | Special: Primitive | Availability: Plentiful"
ITEM.longdesc = "A heavy beating club, with or without spikes. In the dark and claustrophobic trenches, the gun is meaningless."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "arc9_wk_ork_caber"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
