ITEM.name = "Volkite Blaster"
ITEM.description = "Class: Heavy | Range: 80m | Rate of Fire: S/-/3 | Damage: 2d10+6 E | Penetration: 5 | Capacity: 12 | Reload: 3 Full | Special: Mechanicus | Availability: Near Unique"
ITEM.longdesc = "A heavy volkite based weapon. One of the few stil used by the Imperium."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfa_hwh40k_plasmacannon"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
ITEM.auto = 3
