ITEM.name = "Web Gun"
ITEM.description = "Class: Basic | Range: 50m | Rate of Fire: S/-/- | Damage: 1d5+2 R | Penetration: 1 | Capacity: 3 | Reload: 2 Full | Special: Snare/Blast 2 | Availability: Rare"
ITEM.longdesc = "A riot pacifer. Sends large blobs of restraining webs onto the area like the web pistol, but with much more crowd controlling potential."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "sfw_blizzard"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1