ITEM.name = "Witchblade"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10+5 R | Penetration: 0 | Capacity: - | Reload: - | Special: Powerfield, Balanced, Witch's Edge | Availability: Near Unique"
ITEM.longdesc = "The Witchblade is a mystical melee weapon used by Eldar psykers, combining sharp physical strikes with psychic power."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "melee_eldars_witch-blade"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
