ITEM.name = "Warhammer"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10+2 I | Penetration: 1 | Capacity: - | Reload: - | Special: Primitive | Availability: Scarce"
ITEM.longdesc = "Armor or not, the impact alone will find it's mark."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "tfeye_arra"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
