ITEM.name = "Zaythan Warblade"
ITEM.description = "Class: Melee | Range: - | Rate of Fire: - | Damage: 1d10+6 R | Penetration: 0 | Capacity: - | Reload: - | Special: Balanced/Tearing | Availability: Very Rare"
ITEM.longdesc = "This is a chainsword, but created from an unknown xenos race. It looks rather exotic, but still somehow captures the brutal nature of the human sword."
ITEM.model = "models/dizcordum/wh/dot_props/caseb_c.mdl"
ITEM.class = "chainsword"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.ROF = 1
