local PLUGIN = PLUGIN
util.AddNetworkString("openCinematicSplashMenu")
util.AddNetworkString("triggerCinematicSplashMenu")
net.Receive("triggerCinematicSplashMenu", function(_, client)
  if not client:IsAdmin() then return end
  net.Start("triggerCinematicSplashMenu")
  net.WriteString(net.ReadString())
  net.WriteString(net.ReadString())
  net.WriteString(net.ReadString())
  net.WriteUInt(net.ReadUInt(6), 6)
  net.WriteBool(net.ReadBool())
  net.WriteBool(net.ReadBool())
  net.WriteColor(net.ReadColor())
  net.Broadcast()
end)
