ITEM.name = "Armor Upgrade"
ITEM.description = "Upgrade for an armor."
ITEM.category = "Upgrades"
ITEM.model = "models/weapons/w_suitcase_passenger.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 12000
ITEM.slot = 1
ITEM.flag = "1"
ITEM.isUpgrade = true
ITEM.weight = 1.1
ITEM.isArmorUpg = true
