ITEM.name = "Armor Slot +1 Upgrade"
ITEM.description = "An additional slot for an armor suit, for those that have one, such as the bonus Hardware slot on a Bodyweight suit."
ITEM.category = "Upgrades"
ITEM.model = "models/weapons/w_suitcase_passenger.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 12000
ITEM.slot = 1
ITEM.flag = "1"
ITEM.isUpgrade = true
ITEM.weight = 1.1
ITEM.isArmorUpg = true
ITEM.hardwareBoost = 1
